#!/bin/bash

echo "Preparando seu ambiente de estudo!"
idle3 &> /dev/null &
xreader $HOME/Documentos/Faculdade/LearningPython/ATMcPython/Automatize-Tarefas-Macantes-Com-Python.pdf &> /dev/null & 
google-chrome https://github.com/ttund21/LearningPython &> /dev/null & 
google-chrome https://translate.google.com.br/?hl=pt-BR &> /dev/null &
google-chrome http://www.reverso.net/spell-checker/english-spelling-grammar/ &> /dev/null & 

cd $HOME/Documentos/Faculdade/LearningPython

echo "Vai querer executar um git pull? s ou n"
read gitPullResp;

if [ "$gitPullResp" = "s" ];
then
	git pull origin master
fi

cd $HOME/Documentos/Faculdade/LearningPython
exec zsh
